// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtelApi.Data;

#nullable disable

namespace ProtelApi.Migrations
{
    [DbContext(typeof(ProtelDbContext))]
    [Migration("20251121151139_AddUsuarioTable")]
    partial class AddUsuarioTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProtelApi.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CLIENTE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DIRECCION");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DOCUMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FECHA_ACTUALIZACION");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<int>("IdEstadoCliente")
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_CLIENTE");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("PersonaContacto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PERSONA_CONTACTO");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("TELEFONO");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TIPO_CLIENTE");

                    b.HasKey("IdCliente");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("IdEstadoCliente");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("ProtelApi.Models.EstadoCliente", b =>
                {
                    b.Property<int>("IdEstadoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_CLIENTE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEstadoCliente"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdEstadoCliente");

                    b.ToTable("ESTADO_CLIENTE");
                });

            modelBuilder.Entity("ProtelApi.Models.EstadoFactibilidad", b =>
                {
                    b.Property<int>("IdEstadoFactibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_FACTIBILIDAD");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEstadoFactibilidad"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdEstadoFactibilidad");

                    b.ToTable("ESTADO_FACTIBILIDAD");
                });

            modelBuilder.Entity("ProtelApi.Models.Factibilidad", b =>
                {
                    b.Property<int>("IdFactibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FACTIBILIDAD");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFactibilidad"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FECHA_RESPUESTA");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FECHA_SOLICITUD");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<int>("IdEstadoFactibilidad")
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_FACTIBILIDAD");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NOMBRE_PROYECTO");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UBICACION");

                    b.HasKey("IdFactibilidad");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoFactibilidad");

                    b.ToTable("FACTIBILIDAD");
                });

            modelBuilder.Entity("ProtelApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProtelApi.Models.Cliente", b =>
                {
                    b.HasOne("ProtelApi.Models.EstadoCliente", "EstadoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEstadoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoCliente");
                });

            modelBuilder.Entity("ProtelApi.Models.Factibilidad", b =>
                {
                    b.HasOne("ProtelApi.Models.Cliente", "Cliente")
                        .WithMany("Factibilidades")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProtelApi.Models.EstadoFactibilidad", "EstadoFactibilidad")
                        .WithMany("Factibilidades")
                        .HasForeignKey("IdEstadoFactibilidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoFactibilidad");
                });

            modelBuilder.Entity("ProtelApi.Models.Cliente", b =>
                {
                    b.Navigation("Factibilidades");
                });

            modelBuilder.Entity("ProtelApi.Models.EstadoCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("ProtelApi.Models.EstadoFactibilidad", b =>
                {
                    b.Navigation("Factibilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
