CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET=utf8mb4;

START TRANSACTION;
ALTER DATABASE CHARACTER SET utf8mb4;

CREATE TABLE `ESTADO_CLIENTE` (
    `ID_ESTADO_CLIENTE` int NOT NULL AUTO_INCREMENT,
    `NOMBRE` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK_ESTADO_CLIENTE` PRIMARY KEY (`ID_ESTADO_CLIENTE`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `ESTADO_FACTIBILIDAD` (
    `ID_ESTADO_FACTIBILIDAD` int NOT NULL AUTO_INCREMENT,
    `NOMBRE` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK_ESTADO_FACTIBILIDAD` PRIMARY KEY (`ID_ESTADO_FACTIBILIDAD`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `CLIENTE` (
    `ID_CLIENTE` int NOT NULL AUTO_INCREMENT,
    `NOMBRE` varchar(200) CHARACTER SET utf8mb4 NOT NULL,
    `DIRECCION` varchar(300) CHARACTER SET utf8mb4 NOT NULL,
    `TELEFONO` varchar(15) CHARACTER SET utf8mb4 NOT NULL,
    `EMAIL` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
    `FECHA_CREACION` datetime(6) NOT NULL,
    `FECHA_ACTUALIZACION` datetime(6) NOT NULL,
    `ID_ESTADO_CLIENTE` int NOT NULL,
    CONSTRAINT `PK_CLIENTE` PRIMARY KEY (`ID_CLIENTE`),
    CONSTRAINT `FK_CLIENTE_ESTADO_CLIENTE_ID_ESTADO_CLIENTE` FOREIGN KEY (`ID_ESTADO_CLIENTE`) REFERENCES `ESTADO_CLIENTE` (`ID_ESTADO_CLIENTE`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `FACTIBILIDAD` (
    `ID_FACTIBILIDAD` int NOT NULL AUTO_INCREMENT,
    `ID_CLIENTE` int NOT NULL,
    `NOMBRE_PROYECTO` varchar(200) CHARACTER SET utf8mb4 NOT NULL,
    `DESCRIPCION` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `UBICACION` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `FECHA_SOLICITUD` datetime(6) NOT NULL,
    `FECHA_RESPUESTA` datetime(6) NULL,
    `ID_ESTADO_FACTIBILIDAD` int NOT NULL,
    CONSTRAINT `PK_FACTIBILIDAD` PRIMARY KEY (`ID_FACTIBILIDAD`),
    CONSTRAINT `FK_FACTIBILIDAD_CLIENTE_ID_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`) ON DELETE CASCADE,
    CONSTRAINT `FK_FACTIBILIDAD_ESTADO_FACTIBILIDAD_ID_ESTADO_FACTIBILIDAD` FOREIGN KEY (`ID_ESTADO_FACTIBILIDAD`) REFERENCES `ESTADO_FACTIBILIDAD` (`ID_ESTADO_FACTIBILIDAD`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE INDEX `IX_CLIENTE_ID_ESTADO_CLIENTE` ON `CLIENTE` (`ID_ESTADO_CLIENTE`);

CREATE INDEX `IX_FACTIBILIDAD_ID_CLIENTE` ON `FACTIBILIDAD` (`ID_CLIENTE`);

CREATE INDEX `IX_FACTIBILIDAD_ID_ESTADO_FACTIBILIDAD` ON `FACTIBILIDAD` (`ID_ESTADO_FACTIBILIDAD`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20251103183711_InitialCreate', '9.0.10');

ALTER TABLE `CLIENTE` MODIFY COLUMN `FECHA_ACTUALIZACION` datetime(6) NULL;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20251103201915_MakeFechaActualizacionNullable', '9.0.10');

ALTER TABLE `CLIENTE` ADD `DOCUMENTO` varchar(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT '';

ALTER TABLE `CLIENTE` ADD `PERSONA_CONTACTO` varchar(200) CHARACTER SET utf8mb4 NOT NULL DEFAULT '';

ALTER TABLE `CLIENTE` ADD `TIPO_CLIENTE` varchar(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT '';

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20251103214450_AddClienteProperties', '9.0.10');

CREATE UNIQUE INDEX `IX_CLIENTE_DOCUMENTO` ON `CLIENTE` (`DOCUMENTO`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20251103215723_AddUniqueConstraintToDocumento', '9.0.10');

COMMIT;

